#!/bin/bash
#
# Copyright 2018 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SCRIPT="${DIR}/demo_script"

IDX_PREV=0
IDX_CURRENT=1
IDX_NEXT=2

if [[ -f "${DIR}"/.demo_state ]]; then
    IDX_CURRENT=$(cat "${DIR}"/.demo_state)
    IDX_NEXT=$((IDX_CURRENT + 1))
    IDX_PREV=$((IDX_CURRENT - 1))
fi

tput init
ROWS=$(tput lines)
STATUS_LINE=$((ROWS - 1))

while true
do
    CMD_PREV=$(sed "${IDX_PREV}q;d" "${SCRIPT}" 2>/dev/null || echo "")
    CMD_CURRENT=$(sed "${IDX_CURRENT}q;d" "${SCRIPT}" 2>/dev/null || echo "")
    CMD_NEXT=$(sed "${IDX_NEXT}q;d" "${SCRIPT}" 2>/dev/null || echo "")

    rm -rf "${DIR}"/.demo_state
    echo "${IDX_CURRENT}" > "${DIR}"/.demo_state

    clear
    tput cup 0 0
    tput setaf 2
    printf '$ %s\n\n' "${CMD_CURRENT}"
    tput setaf 7
    eval "${CMD_CURRENT}"
    tput cup $(( STATUS_LINE - 1 )) 1
    tput setaf 3
    printf '<<Prev: \e[1;36m %s \e[1;33m >>' "${CMD_PREV}"
    tput cup $STATUS_LINE 1
    printf '<<Next: \e[1;36m %s \e[1;33m >>' "${CMD_NEXT}"

    read -r -n 1 key

    case "${key}" in
    'n' | '' )
        IDX_PREV=$((IDX_PREV + 1))
        IDX_CURRENT=$((IDX_CURRENT + 1))
        IDX_NEXT=$((IDX_NEXT + 1))
        ;;
    'p')
        IDX_PREV=$((IDX_PREV - 1))
        IDX_CURRENT=$((IDX_CURRENT - 1))
        IDX_NEXT=$((IDX_NEXT - 1))
        ;;
    't')
        IDX_PREV=0
        IDX_CURRENT=1
        IDX_NEXT=2
        ;;
    '?')
        clear
        tput setaf 3
        echo
        echo "Usage keys:"
        echo
        echo "  <SPACE> or n - Next page"
        echo "  p            - Previous page"
        echo "  t            - Top page"
        echo "  q            - Quit"
        echo
        read -r -n 1
        ;;
    'q')
        tput reset
        exit 0
        ;;
    esac
done
